### ISSUE TITLE
Agora linker error after upgrading to 3.1.1-beta2

### ISSUE THREAD

**Issue by softsan** [AgoraIO-Community/Agora-RTC-SDK-for-Xamarin#16]
After upgrading this [nuget](https://www.nuget.org/packages/Xamarin.Agora.Full.iOS/3.1.1-beta2) package, i receive following build time errors:
`error MT5211: Native linking failed, undefined Objective-C class: AgoraScreenCaptureParameters. The symbol '_OBJC_CLASS_$_AgoraScreenCaptureParameters' could not be found in any of the libraries or frameworks linked with your application.`

```
Undefined symbols for architecture arm64:
      "_OBJC_CLASS_$_AgoraScreenCaptureParameters", referenced from:
          objc-class-ref in registrar.o
    ld: symbol(s) not found for architecture arm64
    clang : error : linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by sbokatuk** [comment]
hello @softsan , issue fixed use 3.1.2 for iphoneos13 or 3.1.3-beta14 for iphoneos14 sdk

**Comment by neethuflotillatechs** [comment]
Undefined symbol: _OBJC_CLASS_$_AgoraEchoTestConfiguration
